#активные компоненты, которые будут искаться

flags = [
    'Niacinamide 2–5 %',
    'Niacinamide > 5 %',
    'nicotinamide',
    'Vitamin C Ascorbic Acid ≤ 5 %',
    'Ascorbic Acid',
    'Vitamin C Ascorbic Acid > 5 % рН ≤ 4',
    'Vitamin C',
    'Ascorbyl Glucoside',
    'Magnesium Ascorbyl Phosphate',
    '3-O-Ethyl Ascorbic Acid',
    'Sodium Ascorbyl Phosphate',
    'Tetrahexyldecyl Ascorbate',
    'Blue Retinol Bakuchiol',
    'Retinol',
    'Retinol Acetate',
    'Retinol Palmitate',
    'Retinal',
    'Retinyl Propionate',
    'Retinol Retinoate',
    'Retinol encapsulated and liposomal form',
    'Azelaic Acid',
    'Amino Acids + Peptides',
    'EGF',
    'Matrixyl',
    'Leuphasyl',
    'Argireline',
    'SYN-AKE',
    'ВНА-acids',
    'Salicylic Acid 0.5–2 % pH = 3–4',
    'salicylic acid',
    'salicylic',
    'AНА-acids',
    'Lactic Acid',
    'Glycolic Acid',
    'Mandelic Acid 2–10 %* рН = 3–4',
    'cyclandelate',
    'РНА-acids',
    'Lactobionic Acid',
    'Gluconolactone 2–10 % pH = 3–4',
    'Gluconolactone',
    'Benzoyl Peroxide 2.5–5 %',
    'Benzoyl Peroxide'
]

# Список запрещенных компонентов
banned_ingredients = [
    "Benzene",
    "Formaldehyde",
    "Chloroform",
    "Methanol",
    "1,2-Dichloroethane",
    "Nitrosamines",
    "Acetaldehyde",
    "Bis(2-ethylhexyl) phthalate (DEHP)",
    "Dibutyl phthalate (DBP)",
    "Diisobutyl phthalate (DIBP)",
    "Toluene",
    "DDT (Dichlorodiphenyltrichloroethane)",
    "Hexachlorobenzene",
    "Lindane",
    "CI 12150",
    "CI 42555",
    "PABA (Para-aminobenzoic acid)",
    "4-Methylbenzylidene camphor (4-MBC)",
    "Hydroquinone",
    "Cresols",
    "Musk ketone",
    "Musk xylene"
]
features = [
    "увлажняющий",
    "антивозрастной",
    "выравнивает_тон",
    "питательный",
    "для_чувствительной",
    "для_жирной",
    "от_акне",
    "для_проблемной",
    "для_сухой",
    "для_комбинированной",
    "можно_поверх_макияжа",
    "от_черных_точек",
    "сияние_кожи",
    "регенерирующий",
    "матирующий",
    "от_отеков",
    "для_обезвоженной",
    "для_нормальной",
    "spf_защита",
    "пилинг",
    "энзимный",
    "уменьшает_поры",
    "веганский",
    "гипоаллергенный",
    "некомедогенный",
    "с_маслами",
    "с_экстрактами",
    "минеральный",
    "органический",
    "для_подростков",
    "ночной_уход",
    "дневной_уход",
    "успокаивающий",
    "очищающий",
    "отшелушивающий",
    "противовоспалительный",
    "ароматизированный",
    "неароматизированный",
    "гидрофильный",
    "нежирный",
    "плотный",
    "легкий"
]